apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-workflow-creator
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensor-workflow-creator
rules:
  - apiGroups: [argoproj.io]
    resources: [workflows]
    verbs: [create]
  - apiGroups: [argoproj.io]
    resources: [workflowtemplates]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sensor-workflow-creator
subjects:
  - kind: ServiceAccount
    name: sensor-workflow-creator
    namespace: argo-events
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sensor-workflow-creator
